### ISSUE TITLE
remove userID and Password from code?

### ISSUE THREAD

**Issue by Andrewpk** [richardalberto/yiidhl#1]
You may want to remove the userID and password from the code.

xmlpitest can be used without a userid I believe, but in order to use xml pi (with your own userID and password) I believe you may have to fill out this form: http://www.dhl.com/content/dam/downloads/ia_region/express/xmlL_services_web_questionnaire_en.pdf

**Comment by Andrewpk** [comment]
Also, if you're in the US - you have to [register for a DHL account (in order to have a DHL account number) here](http://www.dhl-usa.com/en/express/shipping/open_account.html) first. You'll need an express account to actually receive an account number that you can use to then request access to the XML PI. Webship accounts do not come with account numbers.

This is kind of a pain in the butt.

**Comment by richardalberto** [comment]
Andrew thanks for the feedback, i was looking at this issue and you are right. I added 2 new configuration options dhlSiteId and dhlPassword, so that it can be changed easily. 
But although it says that siteId and password are not required on the test interface, it does fail when you don't provide one, so i used the ones provided by DHL on this site http://xmlpitest-ea.dhl.com/serviceval/jsps/main/Main_menu.jsp in case the user doesn't provide one.

Hope this solves the issue.
